import Head from "next/head";
import CountDown from "../components/CountDown";
import Header from "../components/Header";

const Home = () => {
  return (
    <>
      <Head>
        <title>DS & Algorithms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="text-center min-h-screen">
        <section className="p-8">
          <CountDown />
        </section>
      </main>
    </>
  );
};

export default Home;

