import Head from "next/head";
import Header from "../components/Header";

const Home = () => {
  const myArray = ['Element 0', 'Element 1', 'Element 2', 'Element 3'];
  const myStr = 'MONDAY! MONDAY! MONDAY!';
  return (
    <>
      <Head>
        <title>Ramp ReVamp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="text-center min-h-screen">

      </main>
    </>
  );
};

export default Home;

